### ISSUE TITLE
Añadir alguna forma de avisar al jugador del próximo Level Cap

### ISSUE THREAD

**Issue by Raguzero** [Raguzero/Midele-Crystal-v1.4b-FINAL#5]
Ahora mismo la forma de saberlo es dandote cuenta que tu Pokémon ya no sube mas Experiencia. Debería salir un aviso y/o poder consultar un objeto clave que diga cual es el nivel máximo en dicho momento (como pasa en Midele Emerald).

**Comment by LavenderG** [comment]
Creé un objeto que te dice el level cap (LEVEL_CAP). Ahora falta que alguien te entregue el objeto durante la partida.

**Comment by Raguzero** [comment]
Hecho.
https://github.com/Raguzero/Midele-Crystal-v1.4b-FINAL/commit/0a2ade4387479d5c48594a179097a60ccb0cdfa0
Ahora se recibe el objeto LEVEL CAP desde el comienzo del juego
